NET USE A: /DELETE /Y
NET USE B: /DELETE /Y
:: NET USE C: /DELETE /Y
:: NET USE D: /DELETE /Y
NET USE E: /DELETE /Y
NET USE F: /DELETE /Y
NET USE G: /DELETE /Y
NET USE H: /DELETE /Y
NET USE I: /DELETE /Y
NET USE J: /DELETE /Y
NET USE K: /DELETE /Y
NET USE L: /DELETE /Y
NET USE M: /DELETE /Y
NET USE N: /DELETE /Y
NET USE O: /DELETE /Y
NET USE P: /DELETE /Y
NET USE Q: /DELETE /Y
NET USE R: /DELETE /Y
NET USE S: /DELETE /Y
NET USE T: /DELETE /Y
NET USE U: /DELETE /Y
NET USE V: /DELETE /Y
NET USE W: /DELETE /Y
NET USE X: /DELETE /Y
NET USE Y: /DELETE /Y
NET USE Z: /DELETE /Y

NET USE Z: \\SERVER\SHARE
